from datetime import datetime
from app.models import db, Comment


def seed_comments():
    comment_1 = Comment(body='''You like going to the garage, huh? So does daddy. It's fine, actually. Your mom never wears anything I buy her.  These are Pym Particles, alright? And ever since Hank Pym got snapped out of existence, this is it. This is what we have. We're not making any more.  For the last five years I've been trying to do one thing: Get to right here. That's all it's been about. Bringing everybody back.''', user_id=1, tutorial_id=1, created_at=datetime(2021, 3, 18, 22, 27, 0))
    comment_2 = Comment(body='''We need you. You're new blood. Bunch of tired old mules! That's great. You did the hardest part. You took the jump, you didn't know where you were gonna come down. And that's it. That's those little brave baby steps we gotta take. To try and become whole again, try and find purpose. I went in the ice in '45 right after I met the love of my life. Woke up 70 years later. You gotta move on. Gotta to move on. The world is in our hands. It's left to us guys, and we got to do something with it. Otherwise... Thanos should have killed all of us.  Five years ago, we lost. All of us. We lost friends... We lost family... We lost a part of ourselves. Today, we have a chance to take it all back. You know your teams, you know your missions. Get the stones, get them back. One round trip each. No mistakes. No do-overs. Most of us are going somewhere we know. But it doesn't mean we should know what to expect. Be careful. Look out for each other. This is the fight of our lives. And we're gonna win.  Everyone fails at who they are supposed to be, Thor. The measure of a person, of a hero, is how well they succeed at being who they are.  No, this was a gift. And you're going to be the man you're meant to be.   I got it. There's another way. To retake the Tesseract and acquire new particles. We'll stroll down memory lane. Military installation, Garden State.''', user_id=2, tutorial_id=1, created_at=datetime(2021, 3, 20, 22, 27, 0))
    comment_3 = Comment(body='''The Federales found a room full of bodies. Looks like a bunch of cartel guys. Never even had the chance to get their guns off.  Gotta say, sometimes I miss that giddy optimism. However, high hopes won't help if there's no logical, tangible way for me to safely execute said time heist. I believe the most likely outcome would be our collective demise.  Okay, so, uhh... We just wait around for this Quill guy to show up and then he leads us to the Power Stone, is that it?  We just, wait around for this Quill guy to show up, and then he leads us to the Power Stone, is that it?''', user_id=3, tutorial_id=2, created_at=datetime(2021, 4, 8, 22, 27, 0))
    comment_4 = Comment(body='''Oh my God. I should have stayed on the bus. Going to bed hungry. scrounging for scraps. Your planet was on the brink of collapse. I’m the one who stopped that. Do you know what’s happened since then? The children born have known nothing but full bellies and clear skies. It’s a paradise. Yeah, I think I’m getting the hang of it. Wow! It’s like being the Hulk without actually- (He stumbles on a rock, and a carrier goes by, from which Okoye gives him a dubious look. He stands) I’m okay. I’m okay.''', user_id=4, tutorial_id=2, created_at=datetime(2021, 5, 3, 22, 27, 0))
    comment_5 = Comment(body='''We don’t have the Tesseract. It was destroyed on Asgard. I consider experience, experience. Almighty Thanos. I, Loki, Prince of Asgard… Odinson… The rightful King of Jotunheim, God of Mischief, do hereby pledge to you, my undying fidelity. Attachment to the material is detachment from the spiritual. Tony, listen to me. Thor’s gone. Thanos is coming. It doesn’t matter who you’re talking to or not. Wow. This is a real wake-up call for me. Okay. I’m gonna get a Bowflex. I’m gonna commit. I’m gonna get some dumbbells. Not to each other. Wanda… For two years, we’ve stolen these moments, trying to see if this could work. And… I don’t know. You know what, I’m just gonna speak for myself. – I, I… I think… You’ll know when we’re there. Nivadellir’s forge harnesses the power of a blazing neutron star.  All my life, I dreamed of a day…A moment when you would get what you deserved. And I was always so disappointed. But now…You kill and torture…And you call it mercy. The universe has judged you. You asked it for a prize, and it told you no. You failed. And do you wanna know why? Because you love nothing. No one. Titan was like most planets. Too many mouths, and not enough to go around. And when we faced extinction, I offered a solution. You’ll know when we’re close. Nidavellir’s forge harnesses the blazing power of a Neutron Star. It’s the birthplace of my hammer; it’s truly awesome. Let’s talk about this plan of yours. I think it’s good, except it sucks. So let me do the plan and that way it might be really good.''', user_id=5, tutorial_id=3, created_at=datetime(2021, 5, 18, 22, 27, 0))
    comment_6 = Comment(body='''Yeah. You know what there should be? No more surprises. We’re gonna have a nice dinner tonight. Show off this Harry Winston. Right? And we should have no more surprises. Ever. I should promise you. Tony Stark, I’m Doctor Stephen Strange. I need you to come with me. Oh, uh, congratulations on the wedding, by the way. Hear me, and rejoice. You are about to die at the hands of the Children of Thanos. Be thankful, that your meaningless lives are now contributing to… Hang on, kid. ''', user_id=7, tutorial_id=3, created_at=datetime(2021, 6, 5, 22, 27, 0))
    comment_7 = Comment(body='''My humble personage… bows before your grandeur. No other being has ever had the might, nay the nobility, to wield not one, but two Infinity Stones. The universe lies within your grasp. Stone keeper… Does this chattering animal speak for you? Nidavellir is real? Seriously? I mean, that place is a legend. They make the most powerful, horrific weapons to ever torment the Universe. I would very much like to go there, please. Yeah. Right where I don’t want you to be. This isn’t Coney Island. This isn’t a field trip. It’s one-way ticket. You hear me? Don’t pretend like you thought this through. You could not have possibly thought this through. Flash Gordon? By the way, that’s a compliment. Don’t forget, I’m half human.  So that 50% of me that’s stupid… That’s 100% you.''', user_id=6, tutorial_id=4, created_at=datetime(2021, 6, 22, 22, 27, 0))
    comment_8 = Comment(body='''300 dwarves lived on this ring. I thought if I did what he asked, they’d be safe. I made what he wanted. A device capable of harnessing the power of the stones. Then he killed everyone anyway. All except me. “Your life is yours.” he said “But your hands are mine alone.”''', user_id=8, tutorial_id=4, created_at=datetime(2021, 7, 10, 22, 27, 0))
    comment_9 = Comment(body='''Tony Stark, I’m Doctor Stephen Strange. I need you to come with me. Oh, uh, congratulations on the wedding, by the way. Wong, you’re invited to my wedding.  Who are you kidding, Quill? You’re one sandwich away from fat. Wow. This is a real wake-up call for me. Okay. I’m gonna get a Bowflex. I’m gonna commit. I’m gonna get some dumbbells. Good. Nice. Moral compass.We’re straight.''', user_id=9, tutorial_id=5, created_at=datetime(2021, 7, 19, 22, 27, 0))

    all_comments = [comment_1, comment_2, comment_3, comment_4, comment_5, comment_6, comment_7, comment_8, comment_9]

    db.session.add_all(all_comments)
    db.session.commit()


def undo_comments():
    db.session.execute('TRUNCATE comments RESTART IDENTITY CASCADE;')
    db.session.commit()
