"""update models to include foreign keys

Revision ID: d7f2db497209
Revises: bffda5531558
Create Date: 2021-07-27 11:16:54.005808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7f2db497209'
down_revision = 'bffda5531558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('tutorial_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'tutorials', ['tutorial_id'], ['id'])
    op.drop_column('tiers', 'date')
    op.add_column('tutorials', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('tutorials', sa.Column('style_id', sa.Integer(), nullable=False))
    op.add_column('tutorials', sa.Column('level_id', sa.Integer(), nullable=False))
    op.add_column('tutorials', sa.Column('tier_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tutorials', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'tutorials', 'tiers', ['tier_id'], ['id'])
    op.create_foreign_key(None, 'tutorials', 'styles', ['style_id'], ['id'])
    op.add_column('users', sa.Column('tier_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'tiers', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tier_id')
    op.drop_constraint(None, 'tutorials', type_='foreignkey')
    op.drop_constraint(None, 'tutorials', type_='foreignkey')
    op.drop_constraint(None, 'tutorials', type_='foreignkey')
    op.drop_column('tutorials', 'tier_id')
    op.drop_column('tutorials', 'level_id')
    op.drop_column('tutorials', 'style_id')
    op.drop_column('tutorials', 'date')
    op.add_column('tiers', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'tutorial_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
