"""empty message

Revision ID: 394be291a866
Revises: 213b1eab6083
Create Date: 2021-08-04 15:56:11.335597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394be291a866'
down_revision = '213b1eab6083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('tutorial_id', sa.Integer(), nullable=False))
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'tutorials', ['tutorial_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'tutorial_id')
    # ### end Alembic commands ###
