"""empty message

Revision ID: bc781685b870
Revises: 23c8a00d0c3a
Create Date: 2021-08-04 16:36:50.516590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc781685b870'
down_revision = '23c8a00d0c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorial_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.drop_constraint('tutorial_tags_tutorial_id_fkey', 'tutorial_tags', type_='foreignkey')
    op.create_foreign_key(None, 'tutorial_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tutorial_tags', 'tutorial_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorial_tags', sa.Column('tutorial_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tutorial_tags', type_='foreignkey')
    op.create_foreign_key('tutorial_tags_tutorial_id_fkey', 'tutorial_tags', 'tutorials', ['tutorial_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tutorial_tags', 'tag_id')
    # ### end Alembic commands ###
