"""update user model to include defaults

Revision ID: ee82dbaf6024
Revises: d7f2db497209
Create Date: 2021-07-28 12:59:16.915578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee82dbaf6024'
down_revision = 'd7f2db497209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_updates',
                    existing_type=sa.BOOLEAN(),
                    default=True,
                    nullable=True)
    op.alter_column('users', 'super_user',
                    existing_type=sa.BOOLEAN(),
                    default=False,
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'super_user',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('users', 'email_updates',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###
