"""Update likes join table to include cascade delete

Revision ID: 9abcae790772
Revises: 394be291a866
Create Date: 2021-08-04 15:56:47.090139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abcae790772'
down_revision = '394be291a866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###
